// cs50-2019 pset3 resize.c
// Copies a BMP file
// To resize bmp files
// 1. fread infile to struct xRGB
// 2. using factor process and copy to temp file NewRGB
// 3. fwrite all data to output file

#include <stdio.h>
#include <stdlib.h>

#include "bmp.h" //   struct file

// int main(void)
int main(int argc, char *argv[])
{
    // ensure proper usage
    if (argc != 4)
    {
        fprintf(stderr, "Usage: ./resize f infile outfile\n");
        return 1;
    }

    // remember factor and filenames
    double f = atof(argv[1]);
    char *infile = argv[2];
    char *outfile = argv[3];

    // if y negative integer, return 1
    if (f <= 0)
    {
        printf("The resize factor, must satisfy 0 < n <= 100.\n");
        return 1; // kill the program *****
    }

    // open input file
    FILE *inptr = fopen(infile, "r");
    if (inptr == NULL)
    {
        fprintf(stderr, "Could not open %s.\n", infile);
        return 2;
    }

    // open output file
    FILE *outptr = fopen(outfile, "w");
    if (outptr == NULL)
    {
        fclose(inptr);
        fprintf(stderr, "Could not create %s.\n", outfile);
        return 3;
    }

    // read infile's BITMAPFILEHEADER
    BITMAPFILEHEADER bf;
    fread(&bf, sizeof(BITMAPFILEHEADER), 1, inptr);

    // read infile's BITMAPINFOHEADER
    BITMAPINFOHEADER bi;
    fread(&bi, sizeof(BITMAPINFOHEADER), 1, inptr);

    // ensure infile is (likely) a 24-bit uncompressed BMP 4.0
    if (bf.bfType != 0x4d42 || bf.bfOffBits != 54 || bi.biSize != 40 ||
        bi.biBitCount != 24 || bi.biCompression != 0)
    {
        fclose(outptr);
        fclose(inptr);
        fprintf(stderr, "Unsupported file format.\n");
        return 4;
    }

    // determine padding for original scanlines
    int padding = (4 - (bi.biWidth * sizeof(RGBTRIPLE)) % 4) % 4;

    // storage for infile, only RGB, xRGB
    int xH = abs(bi.biHeight);
    int xW = bi.biWidth;
    RGBTRIPLE xRGB[xH][xW];

    // iterate over infile's scanlines
    for (int i = 0, biHeight = abs(bi.biHeight); i < biHeight; i++)
    {
        // iterate over pixels in scanline
        for (int j = 0; j < bi.biWidth; j++)
        {
            // temporary storage to store original
            RGBTRIPLE triple;

            // read RGB triple from infile
            fread(&triple, sizeof(RGBTRIPLE), 1, inptr);

            // copy to struc xRGB
            xRGB[i][j] = triple;
        }

        // skip over padding, if any .. ?? no idea if require
        fseek(inptr, padding, SEEK_CUR);
    }

    // convert height and width of image with factor, copy to new struct, NewRGB
    int nH = xH * f;
    int nW = xW * f;

    RGBTRIPLE NewRGB[nH][nW];
    for (int na = 0; na < nH; na++)
    {
        for (int nb = 0; nb < nW; nb++)
        {
            int fna = (na / f) + (1 / f / 2);
            int fnb = (nb / f) + (1 / f / 2); //+ 1/f/2 to start from half index
            NewRGB[na][nb] = xRGB[fna][fnb];
        }
    }

    // prepare to Write all data to file
    // new file header, info header, ni.biWidth ,ni.biHeight, biSizeImage, bfSize
    BITMAPFILEHEADER nf;
    nf = bf;
    BITMAPINFOHEADER ni;
    ni = bi;
    ni.biWidth = f * bi.biWidth;   //= nW
    ni.biHeight = f * bi.biHeight; //= nH
    int nipadding = (4 - (ni.biWidth * sizeof(RGBTRIPLE)) % 4) % 4;
    int scanline = (sizeof(RGBTRIPLE) * ni.biWidth) + nipadding;  // size of scanline
    ni.biSizeImage = scanline * abs(ni.biHeight);
    nf.bfSize = sizeof(BITMAPFILEHEADER) + sizeof(BITMAPINFOHEADER) + ni.biSizeImage;

    // write outfile's BITMAPFILEHEADER
    fwrite(&nf, sizeof(BITMAPFILEHEADER), 1, outptr);

    // write outfile's BITMAPINFOHEADER
    fwrite(&ni, sizeof(BITMAPINFOHEADER), 1, outptr);

    // RGB output to file
    for (int i = 0; i < nH; i++)
    {
        for (int j = 0; j < nW; j++)
        {
            // write RGB NewRGB to outfile
            fwrite(&NewRGB[i][j], sizeof(RGBTRIPLE), 1, outptr);
        }

        // add padding if necessary
        for (int k = 0; k < nipadding; k++)
        {
            fputc(0x00, outptr);
        }
    }

    // close infile
    fclose(inptr);

    // close outfile
    fclose(outptr);

    // success
    return 0;
}

/*
large.bmp
nf, sizeof BITMAPFILEHEADER: 14 | write: nf, sizeof BITMAPINFOHEADER: 40
old width: 12 | old height: -12 | old biSizeImage: 432 | old bfSize: 486

~/pset3/resize/more/ $ ./resize
Usage: ./resize f infile outfile
~/pset3/resize/more/ $ style50 ./resize.c
Results generated by style50 v2.7.3
Looks good
~/pset3/resize/more/ $ check50 cs50/problems/2019/x/resize/more
... Waiting for results...........................
Results for cs50/problems/2019/x/resize/more generated by check50 v3.0.8
:) resize.c and bmp.h exist.
:) resize.c compiles.
:) doesn't resize small.bmp when n is 1
:) resizes small.bmp correctly when n is 2
:) resizes small.bmp correctly when n is 3
:) resizes small.bmp correctly when n is 4
:) resizes small.bmp correctly when n is 5
:) resizes large.bmp correctly when n is 2
:) resizes smiley.bmp correctly when n is 2
:) resizes smiley.bmp correctly when n is 3
:) resizes 6x6-pixel BMP to 3x3 correctly when f is 0.5
:) resizes 12x12-pixel BMP to 6x6 correctly when f is 0.5
:) resizes 18x18-pixel BMP to 9x9 correctly when f is 0.5
To see the results in your browser go to https://submit.cs50.io/check50/4f3b51fad2bcc0bf35f36aa377d78b84ba009d6b
~/pset3/resize/more/ $
*/